export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'

export const BOOKING_CHECK_REQUEST = 'BOOKING_CHECK_REQUEST'
export const BOOKING_CHECK_SUCCESS = 'BOOKING_CHECK_SUCCESS'
export const BOOKING_CHECK_FAIL = 'BOOKING_CHECK_FAIL'
export const BOOKING_CHECK_RESET = 'BOOKING_CHECK_RESET'

export const CHECK_DATE_SUCCESS = 'CHECK_DATE_SUCCESS'
export const CHECK_DATE_FAIL = 'CHECK_DATE_FAIL'

export const SHOW_MY_BOOKING_SUCCESS = 'SHOW_MY_BOOKING_SUCCESS'
export const SHOW_MY_BOOKING_FAIL = 'SHOW_MY_BOOKING_FAIL'

export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

export const ADMIN_BOOKINGLIST_REQUEST = 'ADMIN_BOOKINGLIST_REQUEST'
export const ADMIN_BOOKINGLIST_SUCCESS = 'ADMIN_BOOKINGLIST_SUCCESS'
export const ADMIN_BOOKINGLIST_FAIL = 'ADMIN_BOOKINGLIST_FAIL'
export const ADMIN_BOOKINGLIST_RESET = 'ADMIN_BOOKINGLIST_RESET'

export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST'
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS'
export const BOOKING_DELETE_FAIL = 'BOOKING_DELETE_FAIL'
export const BOOKING_DELETE_RESET = 'BOOKING_DELETE_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
