export const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS'
export const ROOMS_LIST_FAIL = 'ROOMS_LIST_FAIL'

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'

export const REVIEW_AVAILABLE_REQUEST = 'REVIEW_AVAILABLE_REQUEST'
export const REVIEW_AVAILABLE_SUCCESS = 'REVIEW_AVAILABLE_SUCCESS'
export const REVIEW_AVAILABLE_FAIL = 'REVIEW_AVAILABLE_FAIL'

export const ADMIN_ROOMLIST_REQUEST = 'ADMIN_ROOMLIST_REQUEST'
export const ADMIN_ROOMLIST_SUCCESS = 'ADMIN_ROOMLIST_SUCCESS'
export const ADMIN_ROOMLIST_FAIL = 'ADMIN_ROOMLIST_FAIL'

export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST'
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS'
export const ROOM_CREATE_RESET = 'ROOM_CREATE_RESET'
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
