export const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS'
export const ROOMS_LIST_FAIL = 'ROOMS_LIST_FAIL'

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_RESET = 'ROOM_DETAILS_RESET'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'

export const REVIEW_AVAILABLE_REQUEST = 'REVIEW_AVAILABLE_REQUEST'
export const REVIEW_AVAILABLE_SUCCESS = 'REVIEW_AVAILABLE_SUCCESS'
export const REVIEW_AVAILABLE_FAIL = 'REVIEW_AVAILABLE_FAIL'

export const ADMIN_ROOMLIST_REQUEST = 'ADMIN_ROOMLIST_REQUEST'
export const ADMIN_ROOMLIST_SUCCESS = 'ADMIN_ROOMLIST_SUCCESS'
export const ADMIN_ROOMLIST_FAIL = 'ADMIN_ROOMLIST_FAIL'

export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST'
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS'
export const ROOM_CREATE_RESET = 'ROOM_CREATE_RESET'
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL'

export const ROOM_DELETE_REQUEST = 'ROOM_DELETE_REQUEST'
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS'
export const ROOM_DELETE_RESET = 'ROOM_DELETE_RESET'
export const ROOM_DELETE_FAIL = 'ROOM_DELETE_FAIL'

export const ROOM_UPDATE_REQUEST = 'ROOM_UPDATE_REQUEST'
export const ROOM_UPDATE_SUCCESS = 'ROOM_UPDATE_SUCCESS'
export const ROOM_UPDATE_RESET = 'ROOM_UPDATE_RESET'
export const ROOM_UPDATE_FAIL = 'ROOM_UPDATE_FAIL'

export const ROOM_REVIEWS_REQUEST = 'ROOM_REVIEWS_REQUEST'
export const ROOM_REVIEWS_SUCCESS = 'ROOM_REVIEWS_SUCCESS'
export const ROOM_REVIEWS_RESET = 'ROOM_REVIEWS_RESET'
export const ROOM_REVIEWS_FAIL = 'ROOM_REVIEWS_FAIL'

export const ROOM_REVIEW_DELETE_REQUEST = 'ROOM_REVIEW_DELETE_REQUEST'
export const ROOM_REVIEW_DELETE_SUCCESS = 'ROOM_REVIEW_DELETE_SUCCESS'
export const ROOM_REVIEW_DELETE_RESET = 'ROOM_REVIEW_DELETE_RESET'
export const ROOM_REVIEW_DELETE_FAIL = 'ROOM_REVIEW_DELETE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
