export const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS'
export const ROOMS_LIST_FAIL = 'ROOMS_LIST_FAIL'

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
